// AUTO-GENERATED by paypal/export_site_data.py — do not edit by hand.
// Source of truth: explainer.py, eval_report.json, captured PayPal events,
// and the live scope probe. Regenerate to update.
//
// Every figure the site renders comes from the running product. If the product
// changes and this file is not regenerated, the numbers are wrong — so treat
// this as generated code, not a place to hardcode claims.

export const product = {
  "explainedTypeCount": 19,
  "eventTypeGroups": [
    {
      "label": "Payouts frozen or stopped",
      "severity": "critical",
      "types": [
        "PAYMENT.PAYOUTS-ITEM.HELD",
        "PAYMENT.PAYOUTS-ITEM.BLOCKED",
        "PAYMENT.PAYOUTS-ITEM.FAILED",
        "PAYMENT.PAYOUTS-ITEM.RETURNED",
        "PAYMENT.PAYOUTS-ITEM.CANCELED"
      ]
    },
    {
      "label": "Payments on hold",
      "severity": "critical",
      "types": [
        "CHECKOUT.PAYMENT-RESOURCE.PAYMENT-ON-HOLD",
        "CHECKOUT.PAYMENT-RESOURCE.PAYMENT-COMPLETED"
      ]
    },
    {
      "label": "Orders",
      "severity": "medium",
      "types": [
        "CHECKOUT.ORDER.APPROVED",
        "CHECKOUT.ORDER.COMPLETED",
        "CHECKOUT.ORDER.DECLINED"
      ]
    },
    {
      "label": "Account restrictions",
      "severity": "high",
      "types": [
        "CUSTOMER.ACCOUNT-ENTITIES.CAPABILITY-UPDATED",
        "CUSTOMER.ACCOUNT-ENTITIES.REQUIREMENTS-UPDATED",
        "CUSTOMER.PAYPAL-ACCOUNT.CHANGED",
        "CUSTOMER.PROFILE.ACCOUNT-CLOSED"
      ]
    },
    {
      "label": "Disputes",
      "severity": "high",
      "types": [
        "RISK.DISPUTE.CREATED",
        "CUSTOMER.DISPUTE.CREATED",
        "CUSTOMER.DISPUTE.RESOLVED"
      ]
    },
    {
      "label": "Subscriptions",
      "severity": "medium",
      "types": [
        "BILLING.SUBSCRIPTION.PAYMENT.FAILED"
      ]
    },
    {
      "label": "Completed",
      "severity": "info",
      "types": [
        "PAYMENT.PAYOUTS-ITEM.SUCCEEDED"
      ]
    }
  ],
  "eventTypes": [
    {
      "name": "PAYMENT.PAYOUTS-ITEM.HELD",
      "group": "Payouts frozen or stopped",
      "severity": "critical",
      "headline": "PayPal held a payout you were sending",
      "impact": "The money has left neither your balance nor the recipient. It is frozen pending review.",
      "confidence": "unknown",
      "actionCount": 4
    },
    {
      "name": "PAYMENT.PAYOUTS-ITEM.BLOCKED",
      "group": "Payouts frozen or stopped",
      "severity": "critical",
      "headline": "PayPal blocked a payout before sending it",
      "impact": "The money did not move. It remains in your balance but cannot be paid out to this recipient.",
      "confidence": "unknown",
      "actionCount": 3
    },
    {
      "name": "PAYMENT.PAYOUTS-ITEM.FAILED",
      "group": "Payouts frozen or stopped",
      "severity": "high",
      "headline": "A payout failed",
      "impact": "The transfer did not complete. Funds were returned to your balance.",
      "confidence": "unknown",
      "actionCount": 2
    },
    {
      "name": "PAYMENT.PAYOUTS-ITEM.RETURNED",
      "group": "Payouts frozen or stopped",
      "severity": "high",
      "headline": "An unclaimed payout was returned",
      "impact": "The recipient did not claim the money in time; it is back in your balance.",
      "confidence": "confirmed",
      "actionCount": 2
    },
    {
      "name": "PAYMENT.PAYOUTS-ITEM.CANCELED",
      "group": "Payouts frozen or stopped",
      "severity": "medium",
      "headline": "A payout was cancelled",
      "impact": "The transfer was stopped before completion. Funds returned to your balance.",
      "confidence": "unknown",
      "actionCount": 2
    },
    {
      "name": "CHECKOUT.PAYMENT-RESOURCE.PAYMENT-ON-HOLD",
      "group": "Payments on hold",
      "severity": "critical",
      "headline": "A payment you received is on hold",
      "impact": "The funds are not yet available to you. PayPal is holding the payment pending its own review.",
      "confidence": "unknown",
      "actionCount": 3
    },
    {
      "name": "CHECKOUT.PAYMENT-RESOURCE.PAYMENT-COMPLETED",
      "group": "Payments on hold",
      "severity": "critical",
      "headline": "A payment completed",
      "impact": "The payment is complete and the funds are yours, subject to any hold period.",
      "confidence": "confirmed",
      "actionCount": 1
    },
    {
      "name": "CHECKOUT.ORDER.APPROVED",
      "group": "Orders",
      "severity": "info",
      "headline": "A buyer approved your order",
      "impact": "Payment was authorised. Capture it to receive the funds.",
      "confidence": "confirmed",
      "actionCount": 1
    },
    {
      "name": "CHECKOUT.ORDER.COMPLETED",
      "group": "Orders",
      "severity": "info",
      "headline": "An order completed",
      "impact": "Payment captured successfully.",
      "confidence": "confirmed",
      "actionCount": 1
    },
    {
      "name": "CHECKOUT.ORDER.DECLINED",
      "group": "Orders",
      "severity": "medium",
      "headline": "An order was declined",
      "impact": "The buyer's payment did not complete. They were not charged.",
      "confidence": "unknown",
      "actionCount": 2
    },
    {
      "name": "CUSTOMER.ACCOUNT-ENTITIES.CAPABILITY-UPDATED",
      "group": "Account restrictions",
      "severity": "high",
      "headline": "A capability on your account changed",
      "impact": "PayPal added or removed a permission \u2014 commonly a payout method, a product, or card acceptance.",
      "confidence": "unknown",
      "actionCount": 3
    },
    {
      "name": "CUSTOMER.ACCOUNT-ENTITIES.REQUIREMENTS-UPDATED",
      "group": "Account restrictions",
      "severity": "high",
      "headline": "PayPal added a requirement to your account",
      "impact": "You are now asked for information \u2014 typically identity, business, or tax documents. This is usually the precursor to a restriction.",
      "confidence": "unknown",
      "actionCount": 3
    },
    {
      "name": "CUSTOMER.PAYPAL-ACCOUNT.CHANGED",
      "group": "Account restrictions",
      "severity": "medium",
      "headline": "Your PayPal account details changed",
      "impact": "Something on the account was modified.",
      "confidence": "unknown",
      "actionCount": 2
    },
    {
      "name": "CUSTOMER.PROFILE.ACCOUNT-CLOSED",
      "group": "Account restrictions",
      "severity": "critical",
      "headline": "Your PayPal account was closed",
      "impact": "The account is closed. Access is limited and payouts stop.",
      "confidence": "unknown",
      "actionCount": 2
    },
    {
      "name": "RISK.DISPUTE.CREATED",
      "group": "Disputes",
      "severity": "high",
      "headline": "A risk dispute was opened on your account",
      "impact": "PayPal's risk system is reviewing activity associated with your account.",
      "confidence": "unknown",
      "actionCount": 3
    },
    {
      "name": "CUSTOMER.DISPUTE.CREATED",
      "group": "Disputes",
      "severity": "high",
      "headline": "A buyer opened a dispute",
      "impact": "Funds for that transaction are held until the dispute is resolved. You have a deadline to submit evidence.",
      "confidence": "confirmed",
      "actionCount": 3
    },
    {
      "name": "CUSTOMER.DISPUTE.RESOLVED",
      "group": "Disputes",
      "severity": "medium",
      "headline": "A dispute was resolved",
      "impact": "PayPal issued a decision on the dispute.",
      "confidence": "confirmed",
      "actionCount": 2
    },
    {
      "name": "BILLING.SUBSCRIPTION.PAYMENT.FAILED",
      "group": "Subscriptions",
      "severity": "medium",
      "headline": "A subscription payment failed",
      "impact": "The renewal did not complete. The subscription may be suspended.",
      "confidence": "unknown",
      "actionCount": 2
    },
    {
      "name": "PAYMENT.PAYOUTS-ITEM.SUCCEEDED",
      "group": "Completed",
      "severity": "info",
      "headline": "A payout completed",
      "impact": "The money reached the recipient.",
      "confidence": "confirmed",
      "actionCount": 1
    }
  ],
  "events": [
    {
      "id": "WH-COC11055RA711503B-3W074927CF383080E",
      "eventType": "CHECKOUT.ORDER.DECLINED",
      "headline": "An order was declined",
      "impact": "The buyer's payment did not complete. They were not charged.",
      "cause": null,
      "confidence": "unknown",
      "actions": [
        "Do not ship \u2014 no payment was taken",
        "Let the buyer retry with another funding source; declines are usually issuer-side"
      ],
      "severity": "medium",
      "kind": "DECLINED",
      "label": "Order declined",
      "amount": null,
      "receiver": null,
      "transactionStatus": null,
      "payoutItemId": null,
      "fieldCount": 0
    },
    {
      "id": "WH-4M0448861G563140B-9EX36365822141321",
      "eventType": "CUSTOMER.DISPUTE.CREATED",
      "headline": "A buyer opened a dispute",
      "impact": "Funds for that transaction are held until the dispute is resolved. You have a deadline to submit evidence.",
      "cause": null,
      "confidence": "confirmed",
      "actions": [
        "Submit evidence before the stated deadline \u2014 missing it loses the case automatically",
        "Have delivery/proof-of-delivery documentation ready \u2014 it is what resolution cases turn on",
        "Keep the buyer-facing message factual and short; a long defensive message tends to work against sellers"
      ],
      "severity": "high",
      "kind": "DISPUTE",
      "label": "Dispute created",
      "amount": null,
      "receiver": null,
      "transactionStatus": null,
      "payoutItemId": null,
      "fieldCount": 1
    },
    {
      "id": "WH-68L35871MU875914X-8DM79009TB591331B",
      "eventType": "PAYMENT.PAYOUTS-ITEM.BLOCKED",
      "headline": "PayPal blocked a payout before sending it",
      "impact": "The money did not move. It remains in your balance but cannot be paid out to this recipient.",
      "cause": null,
      "confidence": "unknown",
      "actions": [
        "Confirm the recipient's email is correct and belongs to you or an authorised account",
        "Check for a notification email stating which check the payout failed",
        "Open a PayPal resolution centre case to appeal, if you believe this is a mistake: paypal.com/resolutioncenter"
      ],
      "severity": "critical",
      "kind": "BLOCKED",
      "label": "Payout blocked",
      "amount": "USD 1.00",
      "receiver": "beamdaddy@paypal.com",
      "transactionStatus": "BLOCKED",
      "payoutItemId": "AYNYWNCHBD8KS",
      "fieldCount": 10
    },
    {
      "id": "WH-68L35871MU875914X-8DM79009TB591331B",
      "eventType": "PAYMENT.PAYOUTS-ITEM.FAILED",
      "headline": "A payout failed",
      "impact": "The transfer did not complete. Funds were returned to your balance.",
      "cause": null,
      "confidence": "unknown",
      "actions": [
        "Check the email PayPal sent for this event; it carries the same case reference",
        "Retry with a different payout method (bank or card) rather than repeating the same one"
      ],
      "severity": "high",
      "kind": "FAILED",
      "label": "Payout failed",
      "amount": "USD 1.00",
      "receiver": "beamdaddy@paypal.com",
      "transactionStatus": "FAILED",
      "payoutItemId": "AYNYWNCHBD8KS",
      "fieldCount": 10
    },
    {
      "id": "WH-68L35871MU875914X-8DM79009TB591331B",
      "eventType": "PAYMENT.PAYOUTS-ITEM.HELD",
      "headline": "PayPal held a payout you were sending",
      "impact": "The money has left neither your balance nor the recipient. It is frozen pending review.",
      "cause": null,
      "confidence": "unknown",
      "actions": [
        "Open a PayPal resolution centre case to appeal, if you believe this is a mistake: paypal.com/resolutioncenter",
        "Do not resend the payout \u2014 a duplicate would be a second, unrecoverable transfer",
        "Check the email PayPal sent for this event; it carries the same case reference",
        "Have delivery/proof-of-delivery documentation ready \u2014 it is what resolution cases turn on"
      ],
      "severity": "critical",
      "kind": "HELD",
      "label": "Payout held by PayPal",
      "amount": "USD 1.00",
      "receiver": "beamdaddy@paypal.com",
      "transactionStatus": "ONHOLD",
      "payoutItemId": "AYNYWNCHBD8KS",
      "fieldCount": 10
    },
    {
      "id": "WH-68L35871MU875914X-8DM79009TB591331B",
      "eventType": "PAYMENT.PAYOUTS-ITEM.RETURNED",
      "headline": "An unclaimed payout was returned",
      "impact": "The recipient did not claim the money in time; it is back in your balance.",
      "cause": "The recipient did not accept the payout within PayPal's claim window.",
      "confidence": "confirmed",
      "actions": [
        "Confirm the recipient's account is active and able to receive payouts",
        "Resend only after confirming with them \u2014 repeated returns can restrict payouts"
      ],
      "severity": "high",
      "kind": "RETURNED",
      "label": "Payout returned",
      "amount": "USD 1.00",
      "receiver": "beamdaddy@paypal.com",
      "transactionStatus": "RETURNED",
      "payoutItemId": "AYNYWNCHBD8KS",
      "fieldCount": 10
    }
  ],
  "evaluation": {
    "scenarios": 20,
    "recall": 0.8,
    "precision": 1.0,
    "f1": 0.889,
    "accuracy": 0.9,
    "confusion": {
      "true_positive": 8,
      "false_negative": 2,
      "false_positive": 0,
      "true_negative": 10
    }
  },
  "causesKnown": 1,
  "causesUnknown": 18,
  "scope": {
    "reportingTransactions": {
      "endpoint": "/v1/reporting/transactions",
      "status": 403,
      "issue": "NOT_AUTHORIZED"
    },
    "reportingBalances": {
      "endpoint": "/v1/reporting/balances",
      "status": 403,
      "issue": "NOT_AUTHORIZED"
    },
    "ordersCreate": {
      "endpoint": "/v2/checkout/orders",
      "status": 201
    },
    "invoicesCreate": {
      "endpoint": "/v2/invoicing/invoices",
      "status": 201
    },
    "identityUserinfo": {
      "endpoint": "/v1/identity/oauth2/userinfo",
      "status": 200
    },
    "webhooksList": {
      "endpoint": "/v1/notifications/webhooks",
      "status": 200
    },
    "payouts": {
      "endpoint": "/v1/payments/payouts",
      "status": 404
    }
  },
  "paypalEventTypesAvailable": 205,
  "subscribedEventTypes": 18,
  "webhookId": "7549251162351621G",
  "integrity": {
    "forgedEventStatus": 400,
    "signatureVerification": "verify-webhook-signature",
    "dedupKey": "transmission_id + event_type",
    "redeliveryPolicy": "25 attempts over 3 days"
  },
  "limits": {
    "maxTokensFloor": 2048,
    "followUpDeadlineSeconds": 8,
    "rateLimitObserved": "429 on 4 of 6 rapid calls",
    "modelChain": [
      "gemini-3-flash-preview",
      "gemini-flash-latest",
      "gemini-3.1-flash-lite-preview"
    ]
  }
} as const;

export type Product = typeof product;
export type CapturedEvent = Product['events'][number];
export type ExplainedType = Product['eventTypes'][number];
